// ─── DOLLOP SITE CONFIG ────────────────────────────────────────────────────
// This file holds fallback defaults used if the remote config cannot be loaded.
// DO NOT edit this file to change live settings — use the admin panel instead.

const APPS_SCRIPT_URL = 'https://script.google.com/a/macros/jump.com.my/s/AKfycby4nUS08bJwysLfor3cQWQosJD66rloMnZWeRpkE6mD8vgEHbv5d7Ygghs40nHGSbl87w/exec';
const COMPANY_WHATSAPP = '60142676333';

const DEFAULT_CONFIG = {
  SOLD_OUT:               true,   // true = disable ordering, show "Sold Out"
  MAX_QTY:                24,     // maximum cups per order
  PROMO_ACTIVE:           true,   // true = show "Buy 5 Free 1" badge
  PROMO_THRESHOLD:        5,      // buy X cups...
  PROMO_FREE:             1,      // ...get Y free
  ANNOUNCEMENT_ACTIVE:    false,  // true = show popup on page load
  ANNOUNCEMENT_IMAGE_URL: '',     // direct image URL or Google Drive share link
  ANNOUNCEMENT_LINK:      'product.html',
};

// Applied once config is fetched (or falls back to DEFAULT_CONFIG)
window.SITE_CFG = Object.assign({}, DEFAULT_CONFIG);

function toDriveDirectUrl(url) {
  if (!url) return '';
  var m = url.match(/\/file\/d\/([^/?]+)/);
  return m ? 'https://drive.google.com/uc?export=view&id=' + m[1] : url;
}
